<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/15 0015
 * Time: 上午 11:20
 */
namespace app\admin\model;
use think\Db;
use think\Model;

class Goods extends Model{
    protected $pk="goods_id";
    protected $autoWriteTimestamp=true;
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Goods::event('before_insert',function($goods){
            $goods['goods_sn']="SP".uniqid();
            $goods['add_time']=time();
        });
        Goods::event('after_insert',function($goods){
            //入库后会有goods_id  取出主键值;
            $goods_id=$goods['goods_id'];
            $postData=input('post.');
            $goods_attr_values=$postData['goodsAttrValue'];
            $goods_attr_price=$postData['goodsAttrPrice'];
            foreach ($goods_attr_values as $attr_id=>$attr_values){
                if(is_array($attr_values)){
                    //单选属性
                    foreach ($attr_values as $k=>$single_attr_value){
                        $data=[
                            'goods_id'=>$goods_id,
                            'attr_id'  =>$attr_id,
                            'attr_value' =>$single_attr_value,
                            'attr_price'  =>$goods_attr_price[$attr_id][$k]
                        ];
                        Db::name('goods_attr')->insert($data);
                    }
                }else{
                    //唯一属性
                    $data=[
                        'goods_id'=>$goods_id,
                        'attr_id'  =>$attr_id,
                        'attr_value' =>$attr_values
                    ];
                    Db::name('goods_attr')->insert($data);
                }
            }
        });
    }
}