<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/14 0014
 * Time: 上午 1:26
 */
namespace app\admin\model;
use think\Model;

class Type extends Model{
    protected $pk='type_id';
    protected $autoWriteTimestamp=true;
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Type::event('before_insert',function ($type){
            $type['mark']=trim($type['mark']);
        });
        Type::event('before_update',function ($type){
            $type['mark']=trim($type['mark']);
        });
    }
}