<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/12 0012
 * Time: 下午 2:34
 */
namespace app\admin\controller;
use think\Controller;

class CommonController extends Controller{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!session('username')){
            $this->redirect('admin/public/login');
        }
        //获取当前用户请求的控制器,方法,拼接成字符串
        $nowrequest=strtolower(request()->controller().'/'.request()->action());
        //在session中获取当前用户的请求权限的数组,
        $nowuserAuth=session('visitorAuth');
        //判断当前用户是否是超级管理员,或者是在请求主页,是就允许用户操作,
        if($nowuserAuth=='*' ||strtolower(request()->controller())=='index'){
            return;  //退出当前方法,允许请求
        }else{
            if(!in_array($nowrequest,$nowuserAuth)){
                if(request()->isAjax()){
                    echo json_encode(['status'=>-1,'message'=>"无权限操作请联系管理员"]);
                    die;
                }
                $this->redirect("admin/index/index");
            }
        }
    }
}