<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/16 0016
 * Time: 下午 9:25
 */
namespace app\home\model;
use think\Model;

class Member extends Model{
    protected $pk='uid';
    protected $autoWriteTimestamp=true;
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Member::event('before_insert',function($member){
             $member['password']=md5($member['password'].config('password_salt'));
        });
    }
    public function checkUser($username,$password){
        $condition=['username'=>$username,'password'=>$password];
        $userInfo=$this->where($condition)->find();
        if($userInfo){
            session('home_username',$userInfo['username']);
            session('uid',$userInfo['uid']);
            return true;
        }else{
            return false;
        }
    }
}